name: swipe_card_example
description: Example of swipe card application.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.3.0
  flutter: ^3.22.3

dependencies:
  flutter:
    sdk: flutter
  swipe_card:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
