name: swipe_card_example
description: Example of swipe card application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  swipe_card:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter