name: swipe_card
description: A Flutter plugin to create a stack of boolean swipe cards with
  gesture, animation and callbacks.
version: 1.3.0
homepage: null

environment:
  sdk: ^3.3.0
  flutter: ^3.22.3

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
